library(dplyr)
library(Matrix)
library(Seurat)
library(ggplot2)


for(i in c("cereb1","cereb2","hippo","kidney","liver")){
  expr <- data.table::fread(
    input = paste0("DGE/ed0/slide_",i,"_ed0_visium_Feb2021.edit.csv.gz"), # generated by Spatial_DGE_merge.ipynb
    sep = ",",
    data.table = FALSE
  )
  rn_raw <- toupper(x = expr[, 1])
  expr <- expr[!duplicated(rn_raw),]
  rownames(x = expr) <- toupper(x = expr[, 1])
  # colnames(x = expr) <- toupper(x = colnames(x = expr))
  expr <- expr[,-1]
  expr <- expr[rowSums(expr)>0,]
  # expr_subset <- expr[,puck_subset]
  slide.seq <- CreateSeuratObject(
    counts = expr,
    project = 'SlideSeq',
    assay = 'Spatial'
  )
  positions <- read.table(paste0("location/",i,"_loc.tsv"),header = T) %>% unique
  rownames(positions) <- paste0("export_",positions$d_ind_bc,"-1")
  positions <- positions[, 2:3]
  positions_subset <- positions[colnames(expr),]
  slide.seq[['image']] <- new(
    Class = 'SlideSeq',
    assay = "Spatial",
    coordinates = positions_subset
  )
  
  slide.seq$log_nCount_Spatial <- log(slide.seq$nCount_Spatial)
  plot_count <- SpatialFeaturePlot(slide.seq, features = "log_nCount_Spatial",stroke = 0,pt.size.factor = 1)
  slide.seq <- NormalizeData(slide.seq,normalization.method = "LogNormalize", scale.factor = 10000,verbose = F)
  slide.seq <- FindVariableFeatures(slide.seq,selection.method="vst",nfeatures = 3000,verbose = F)
  slide.seq <- ScaleData(slide.seq,verbose=F)
  slide.seq <- RunPCA(slide.seq)
  slide.seq <- RunUMAP(slide.seq, dims = 1:30)
  slide.seq <- FindNeighbors(slide.seq, dims = 1:30)
  slide.seq <- FindClusters(slide.seq, resolution = 0.6, verbose = FALSE)
  plot1 <- DimPlot(slide.seq, reduction = "umap", label = TRUE)
  plot2 <- SpatialDimPlot(slide.seq, stroke = 0,pt.size.factor = 1)
  saveRDS(slide.seq,paste0("rds/",i,"_ed0_slide.rds"))
}


get_grid <- function(dat){
  d_index_df <- unique(dat$d_index) %>% str_split_fixed("_",n = 2) %>% as.data.frame()
  colnames(d_index_df) <- c("split_row","split_col")

  d_index_row <- unique(d_index_df$split_row) %>% as.character %>% as.numeric()
  d_index_col <- unique(d_index_df$split_col) %>% as.character  %>% as.numeric()
  
  min_vertical <- dat$x %>% min
  min_horizontal <- dat$y %>% min
  
  h_vec <- c(min_horizontal)
  v_vec <- c(min_vertical)
  
  add_df <- dat$d_index %>% str_split_fixed("_",n = 2) %>% as.data.frame()
  colnames(add_df) <- c("split_row","split_col")
  dat <- cbind(dat,add_df)
  
  for(i in d_index_row){
    tmp_v <- filter(dat,split_row==as.character(i))$x %>% max
    v_vec <- c(v_vec,tmp_v)
  }
  
  for(i in d_index_col){
    tmp_h <- filter(dat,split_col==as.character(i))$y %>% max
    h_vec <- c(h_vec,tmp_h)
  }
  
  L <- list(vert = v_vec,hori=h_vec)
  return(L)
}



#hippo
slide.seq <- readRDS("rds/hippo_ed0_slide.rds")
slide_loc_new <- as.data.frame(slide.seq@images$image@coordinates)
slide_loc_new$clusters <- factor(slide.seq$Spatial_snn_res.0.6,levels = as.numeric(levels(slide.seq$Spatial_snn_res.0.6)) %>% sort)
slide_loc_new <- cbind(slide_loc_new,slide.seq@reductions$umap@cell.embeddings)

library(RColorBrewer)
library(viridis)
library(ggthemes)
n <- 34
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
set.seed(7)
my_col_viri <- sample(col_vector, n)

coord_aligned_10 <- read.table("data/slide_to_vis_exp10_aligned.tsv",sep="\t",row.names = 1,header = T)
df.grid  <- get_grid(coord_aligned_10)

g1 <- ggplot(slide_loc_new,aes(x=x,y=y,col=clusters))+
  theme_map()+
  geom_point(size=0.01)+
  coord_fixed(ratio=1)+
  # scale_color_manual(values = my_col_viri2)+
  scale_color_manual(values = my_col_viri)+
  guides(colour=guide_legend(override.aes = list(alpha=1,size=3)))+
  NoLegend()+
  geom_hline(yintercept =  df.grid[["hori"]], size=0.3481)+
  geom_vline(xintercept =  df.grid[["vert"]], size=0.3481)+
  scale_x_continuous(limits = c(min(df.grid[["vert"]])-50, max(df.grid[["vert"]]+50)), expand = c(0, 0))+
  scale_y_continuous(limits = c(min(df.grid[["hori"]])-50, max(df.grid[["hori"]]+50)), expand = c(0, 0))
g1

ggsave("plot_220224//hippo_ed0_spatial.jpeg",g1,width = 10,height = 10,units = "cm",dpi=600)
ggsave("plot_220224//hippo_ed0_spatial.pdf",g1,width = 10,height = 10,units = "cm")




#cereb1
slide.seq <- readRDS("rds/cereb1_ed0_slide.rds")
slide_loc_new <- as.data.frame(slide.seq@images$image@coordinates)
slide_loc_new$clusters <- factor(slide.seq$Spatial_snn_res.0.6,levels = as.numeric(levels(slide.seq$Spatial_snn_res.0.6)) %>% sort)
slide_loc_new <- cbind(slide_loc_new,slide.seq@reductions$umap@cell.embeddings)

n <- 17
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
set.seed(29)
my_col_viri <- sample(col_vector, n)


g1 <- ggplot(slide_loc_new,aes(x=x,y=y,col=clusters))+
  theme_void()+
  geom_point(size=0.02)+
  coord_fixed(ratio=1)+
  # scale_color_manual(values = my_col_viri2)+
  scale_color_manual(values = my_col_viri)+
  guides(colour=guide_legend(override.aes = list(alpha=1,size=3)))+
  NoLegend()

coord_aligned_10 <- read.table("data/cereb1_exp10_aligned.tsv",sep="\t",row.names = 1,header = T)
df.grid  <- get_grid(coord_aligned_10)

g1 <- g1+
  geom_hline(yintercept =  df.grid[["hori"]], size=0.3481)+
  geom_vline(xintercept =  df.grid[["vert"]], size=0.3481)+
  scale_x_continuous(limits = c(min(df.grid[["vert"]])-50, max(df.grid[["vert"]]+50)), expand = c(0, 0))+
  scale_y_continuous(limits = c(min(df.grid[["hori"]])-50, max(df.grid[["hori"]]+50)), expand = c(0, 0))
g1

ggsave("plot_220224///cereb1_ed0_spatial.jpeg",g1,width = 10,height = 10,units = "cm",dpi=600)
ggsave("plot_220224///cereb1_ed0_spatial.pdf",g1,width = 10,height = 10,units = "cm")




#cereb2
slide.seq <- readRDS("rds/cereb2_ed0_slide.rds")
slide_loc_new <- as.data.frame(slide.seq@images$image@coordinates)
slide_loc_new$clusters <- factor(slide.seq$Spatial_snn_res.0.6,levels = as.numeric(levels(slide.seq$Spatial_snn_res.0.6)) %>% sort)
slide_loc_new <- cbind(slide_loc_new,slide.seq@reductions$umap@cell.embeddings)

n <- 27
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
set.seed(11)
my_col_viri <- sample(col_vector, n)

g1 <- ggplot(slide_loc_new,aes(x=x,y=y,col=clusters))+
  theme_void()+
  geom_point(size=0.01)+
  coord_fixed(ratio=1)+
  scale_color_manual(values = my_col_viri)+
  guides(colour=guide_legend(override.aes = list(alpha=1,size=3)))+
  NoLegend()

coord_aligned_10 <- read.table("data/cereb2_exp10_aligned.tsv",sep="\t",row.names = 1,header = T)
df.grid  <- get_grid(coord_aligned_10)

g1 <- g1+
  geom_hline(yintercept =  df.grid[["hori"]], size=0.3481)+
  geom_vline(xintercept =  df.grid[["vert"]], size=0.3481)+
  scale_x_continuous(limits = c(min(df.grid[["vert"]])-50, max(df.grid[["vert"]]+50)), expand = c(0, 0))+
  scale_y_continuous(limits = c(min(df.grid[["hori"]])-50, max(df.grid[["hori"]]+50)), expand = c(0, 0))
g1

ggsave("plot_220224///cereb2_ed0_spatial.jpeg",g1,width = 10,height = 10,units = "cm",dpi=600)
ggsave("plot_220224//cereb2_ed0_spatial.pdf",g1,width = 10,height = 10,units = "cm")




#liver
slide.seq <- readRDS("rds/liver_ed0_slide.rds")
slide_loc_new <- as.data.frame(slide.seq@images$image@coordinates)
slide_loc_new$clusters <- factor(slide.seq$Spatial_snn_res.0.6,levels = as.numeric(levels(slide.seq$Spatial_snn_res.0.6)) %>% sort)
slide_loc_new <- cbind(slide_loc_new,slide.seq@reductions$umap@cell.embeddings)

n <- 8
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
set.seed(26)
my_col_viri <- sample(col_vector, n)

g1 <- ggplot(slide_loc_new,aes(x=x,y=y,col=clusters))+
  theme_void()+
  geom_point(size=0.01)+
  coord_fixed(ratio=1)+
  scale_color_manual(values = my_col_viri)+
  guides(colour=guide_legend(override.aes = list(alpha=1,size=3)))+
  NoLegend()

coord_aligned_10 <- read.table("data/liver_exp10_aligned.tsv",sep="\t",row.names = 1,header = T)
df.grid  <- get_grid(coord_aligned_10)

g1 <- g1+
  geom_hline(yintercept =  df.grid[["hori"]], size=0.3481)+
  geom_vline(xintercept =  df.grid[["vert"]], size=0.3481)+
  scale_x_continuous(limits = c(min(df.grid[["vert"]])-50, max(df.grid[["vert"]]+50)), expand = c(0, 0))+
  scale_y_continuous(limits = c(min(df.grid[["hori"]])-50, max(df.grid[["hori"]]+50)), expand = c(0, 0))
g1

ggsave("plot_220224///liver_ed0_spatial.jpeg",g1,width = 10,height = 10,units = "cm",dpi=600)
ggsave("plot_220224/liver_ed0_spatial.pdf",g1,width = 10,height = 10,units = "cm")




#kidney
slide.seq <- readRDS("rds/kidney_ed0_slide.rds")
slide_loc_new <- as.data.frame(slide.seq@images$image@coordinates)
slide_loc_new$clusters <- factor(slide.seq$Spatial_snn_res.0.6,levels = as.numeric(levels(slide.seq$Spatial_snn_res.0.6)) %>% sort)
slide_loc_new <- cbind(slide_loc_new,slide.seq@reductions$umap@cell.embeddings)

n <- 15
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
set.seed(29)
my_col_viri <- sample(col_vector, n)

g1 <- ggplot(slide_loc_new,aes(x=x,y=y,col=clusters))+
  theme_void()+
  geom_point(size=0.01)+
  coord_fixed(ratio=1)+
  scale_color_manual(values = my_col_viri)+
  guides(colour=guide_legend(override.aes = list(alpha=1,size=3)))+
  NoLegend()

coord_aligned_10 <- read.table("data/kidney_exp10_aligned.tsv",sep="\t",row.names = 1,header = T)
df.grid  <- get_grid(coord_aligned_10)

g1 <- g1+
  geom_hline(yintercept =  df.grid[["hori"]], size=0.3481)+
  geom_vline(xintercept =  df.grid[["vert"]], size=0.3481)+
  scale_x_continuous(limits = c(min(df.grid[["vert"]])-50, max(df.grid[["vert"]]+50)), expand = c(0, 0))+
  scale_y_continuous(limits = c(min(df.grid[["hori"]])-50, max(df.grid[["hori"]]+50)), expand = c(0, 0))
g1

ggsave("plot_220224//kidney_ed0_spatial.jpeg",g1,width = 10,height = 10,units = "cm",dpi=600)
ggsave("plot_220224//kidney_ed0_spatial.pdf",g1,width = 10,height = 10,units = "cm")
